---

- name: "cron: Configure cron MAILTO={{ freebsd_ports_portsnap_cron_mailto }}"
  community.general.cronvar:
    name: MAILTO
    value: "{{ ports_portsnap_cron_mailto }}"
    user: "{{ ports_portsnap_cron_user }}"
  when: ports_portsnap_cron_mailto|length > 0

- name: "cron: Configure cron to fetch a compressed snapshot of the ports tree"
  ansible.builtin.cron:
    name: "{{ ports_portsnap_cron_name }}"
    job: "{{ ports_portsnap_cron_command }}"
    user: "{{ ports_portsnap_cron_user }}"
    month: "{{ ports_portsnap_cron_month|d(omit) }}"
    day: "{{ ports_portsnap_cron_day|d(omit) }}"
    hour: "{{ ports_portsnap_cron_hour|d(omit) }}"
    minute: "{{ ports_portsnap_cron_minute|d(omit) }}"
    weekday: "{{ ports_portsnap_cron_weekday|d(omit) }}"
    special_time: "{{ ports_portsnap_cron_special_time|d(omit) }}"
    backup: "{{ ports_portsnap_cron_backup|d(omit) }}"

# EOF
...
