---
# tasks for freebsd-ports

- include: cron.yml
  when: freebsd_ports_portsnap_cron_enable|lower == "yes"
  tags:
    - freebsd_ports_cron
    - freebsd_ports_all

- include: ports.yml
  tags:
    - bsd_packages
    - bsd_ports
    - freebsd_ports_install
    - freebsd_ports_all

# EOF
...
