---
# tasks for freebsd_ports

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags: [ports_vars, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: ports_debug|bool
  tags: ports_debug

- block:

    - name: Import ports_delete.yml
      ansible.builtin.import_tasks: ports_delete.yml
      tags: ports_delete

    - name: Import ports_install.yml
      ansible.builtin.import_tasks: ports_install.yml
      tags: ports_install

  when: freebsd_install_method|lower == 'ports'

- name: Import cron.yml
  ansible.builtin.import_tasks: cron.yml
  when: ports_portsnap_cron_enable|bool
  tags: ports_cron

- name: Import stat.yml
  ansible.builtin.import_tasks: stat.yml
  when: ports_stat|bool
  tags: ports_stat

# EOF
...
