---
# tasks for freebsd_ports

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags: [ports_vars, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: ports_debug|bool
  tags: ports_debug

- name: Import ports.yml
  ansible.builtin.import_tasks: ports.yml
  when: freebsd_install_method|lower == "ports"
  tags: ports_install

- name: Import cron.yml
  ansible.builtin.import_tasks: cron.yml
  when: ports_portsnap_cron_enable|bool
  tags: ports_cron

# EOF
...
