---
# tasks for freebsd-ports

- import_tasks: vars.yml
  tags: [freebsd_ports_vars, always]

- import_tasks: debug.yml
  when: freebsd_ports_debug|bool
  tags: [freebsd_ports_debug, always]

- import_tasks: ports.yml
  when: freebsd_install_method|lower == "ports"
  tags: freebsd_ports_install

- import_tasks: cron.yml
  when: freebsd_ports_portsnap_cron_enable|bool
  tags: freebsd_ports_cron

# EOF
...
