---

- name: Install ports
  portinstall: >
    name="{{ item }}"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  with_items: "{{ freebsd_ports_list }}"
  tags: freebsd_ports_list

# EOF
...
