---

- name: "ports_install: Install individually from all lists in pkg_dict"
  block:

    - name: "ports_install: Debug individually from all lists in pkg_dict"
      ansible.builtin.debug:
        msg: "{{ item.0.pkglist }}: {{ item.1 }}"
      loop: "{{ pkg_dict|subelements('packages') }}"
      loop_control:
        label: "{{ item.0.pkglist }}: {{ item.1 }}"
      when: ports_debug|bool

    - name: "ports_install: Install individually from all lists in pkg_dict"
      community.general.portinstall:
        name: "{{ item.1 }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ pkg_dict|subelements('packages') }}"
      loop_control:
        label: "{{ item.0.pkglist }}: {{ item.1 }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"
      when: not ports_dryrun|bool

    - name: "ports_install: Debug result"
      ansible.builtin.debug:
        var: result
      when: ports_debug|bool

  when: pkg_dict_all|d(false)|bool
  tags: ports_install_all_indivindually

- name: "ports_install: Install individually from selected lists in pkg_dict"
  block:

    - name: "ports_install: Debug individually from selected lists in pkg_dict"
      ansible.builtin.debug:
        msg: "{{ item.0.pkglist }}: {{ item.1 }}"
      loop: "{{ pkg_dict|selectattr('pkglist', 'in', pkg_dict_select)|
                         subelements('packages') }}"
      loop_control:
        label: "{{ item.0.pkglist }}: {{ item.1 }}"
      when: ports_debug|bool

    - name: "ports_install: Install individually from selected lists in pkg_dict"
      community.general.portinstall:
        name: "{{ item.1 }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ pkg_dict|selectattr('pkglist', 'in', pkg_dict_select)|
                         subelements('packages') }}"
      loop_control:
        label: "{{ item.0.pkglist }}: {{ item.1 }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"
      when: not ports_dryrun|bool

    - name: "ports_install: Debug result"
      ansible.builtin.debug:
        var: result
      when: ports_debug|bool

  when: pkg_dict_select|length > 0
  tags: ports_install_selected_indivindually

- name: "ports_install: Install individually from list pkg_list"
  block:

    - name: "ports_install: Debug individually from list pkg_list"
      ansible.builtin.debug:
        var: item
      loop: "{{ pkg_list }}"
      when: ports_debug|bool

    - name: "ports_install: Install individually from list pkg_list"
      community.general.portinstall:
        name: "{{ item }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ pkg_list }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"
      when: not ports_dryrun|bool

    - name: "ports_install: Debug result"
      ansible.builtin.debug:
        var: result
      when: ports_debug|bool

  when: pkg_list|length > 0
  tags: ports_install_list_indivindually

# EOF
...
