---

- name: "ports: Debug list ports from a dictionary"
  debug:
    msg: "{{ item.1 }}"
  loop: "{{ pkg_dict|subelements('packages') }}"
  when: freebsd_ports_debug|bool

- name: "ports: Install ports from a dictionary"
  portinstall:
    name: "{{ item.1 }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ pkg_dict|subelements('packages') }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: not freebsd_ports_dryrun|bool

- name: "ports: Install ports from a list"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ pkg_list }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: not freebsd_ports_dryrun|bool

- name: "ports: Deinstall ports from a list"
  portinstall:
    state: absent
    name: "{{ item }}"
  loop: "{{ pkg_list_deinstall }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: not freebsd_ports_dryrun|bool

# EOF
...
