---

# INSTALL

- name: "ports: Install all lists"
  block:
    - name: "ports: Install all lists from pkg_dict"
      community.general.portinstall:
        name: "{{ item.1 }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ query('subelements', pkg_dict, 'packages') }}"
      loop_control:
        label: "{{ item.0.pkglist }}: {{ item.1 }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"
    - name: "ports: Debug result"
      ansible.builtin.debug:
        var: result
      when: ports_debug|bool
  when: pkg_dict_all|d(false)|bool

- name: "ports: Install selected lists"
  block:
    - name: "ports: Install selected lists from pkg_dict"
      community.general.portinstall:
        name: "{{ item.1 }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ query('subelements', pkg_dict, 'packages') }}"
      loop_control:
        label: "{{ item.0.pkglist }}: {{ item.1 }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"
      when: pkg_dict_select[item.0.pkglist]|d(false)|bool
    - name: "ports: Debug result"
      ansible.builtin.debug:
        var: result
      when: ports_debug|bool
  when: pkg_dict_select|length > 0

- name: "ports: Install single list"
  block:
    - name: "ports: Install ports from a list"
      community.general.portinstall:
        name: "{{ item }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ pkg_list }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"
    - name: "ports: Debug result"
      ansible.builtin.debug:
        var: result
      when: ports_debug|bool
  when: pkg_list|length > 0

# DEINSTALL

- name: "ports: Deinstall single list"
  block:
    - name: "ports: Deinstall ports from a list"
      community.general.portinstall:
        state: absent
        name: "{{ item }}"
      loop: "{{ pkg_list_deinstall }}"
      register: result
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"
    - name: "ports: Debug result"
      ansible.builtin.debug:
        var: result
      when: ports_debug|bool
  when: pkg_list_deinstall|length > 0

# EOF
...
