---

- name: If ports_config enabled test existence of {{ ports_portsnap_conf_file }}
  when: ports_config | bool
  block:

    - name: "Sanity: Stat {{ ports_portsnap_conf_file }}"
      ansible.builtin.stat:
        path: "{{ ports_portsnap_conf_file }}"
      register: result

    - name: "Sanity: If ports_config enabled test existence of {{ ports_portsnap_conf_file }}"
      ansible.builtin.assert:
        that: result.stat.exists
        fail_msg: "[ERR] {{ ports_portsnap_conf_file }} required if ports_config is enabled."

# EOF
...
