---
- name: Get outdated ports
  when: ports_outdated_enable | bool
  block:

    - name: "Stat: Get outdated ports (this may take a while)"
      ansible.builtin.command: pkg version -l "<"
      register: ports_outdated_out
      changed_when: false

    - name: "Stat: Debug outdated ports"
      ansible.builtin.debug:
        var: ports_outdated
      when: ports_debug | bool
      run_once: true

  rescue:

    - name: "Stat: rescue: Debug"
      ansible.builtin.debug:
        msg: |
          [ERR] Get outdated ports failed:
          {{ ansible_failed_result }}
          End host.

    - name: "Stat: rescue: End host"
      ansible.builtin.meta: end_host

# EOF
