---
- name: Update ports
  block:

    - name: "Update: Update ports (this may take a while)"
      ansible.builtin.command: portsnap auto
      register: ports_updated_out
      changed_when: false

    - name: "Stat: Debug update ports ports_debug={{ ports_debug }}"
      ansible.builtin.debug:
        var: ports_updated_out
      when: ports_debug | bool

  rescue:

    - name: "Update: rescue: Debug"
      ansible.builtin.debug:
        msg: |
          [ERR] Update ports failed:
          {{ ansible_failed_result }}
          End host.

    - name: "Stat: rescue: End host"
      ansible.builtin.meta: end_host

# EOF
